services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - my-net1
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://43.200.245.38:3306/congcongjoa?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=congcongjoa
      - SPRING_DATASOURCE_PASSWORD=12345678

    volumes:
      - ./nginx/ssl/accounts:/etc/nginx/ssl/accounts
    restart: always

  nginx:
    image: nginx:latest
    networks:
      - my-net1
    restart: always
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl/accounts:/etc/nginx/ssl/accounts
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend

networks:
  my-net1:
    driver: bridge
