server:
  port: 9090
  servlet:
    session:
      timeout: 24h
spring:
  datasource:
    url: jdbc:mysql://43.200.245.38:3306/congcongjoa
    username: congcongjoa
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 100
      minimum-idle: 10
      idle-timeout: 600000      # 10분
      max-lifetime: 1800000     # 30분
      connection-timeout: 30000
      validation-timeout: 5000
      leak-detection-threshold: 1795000 # (29분 55초)
      pool-name: HikariPool
      register-mbeans: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    redis:
      host: 43.200.245.38
      port: 6379
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    enums:
      use-class-for-enum-values: true
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE

custom:
  jwt:
    secretKey: jasdaasdlnwlernlxchopASjfdwaswooseokdf1d65s4d6g4a6sd4fsdahnthjpower